name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  file:  # id of input
    description: 'A json file to read'
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node12'
  main: 'dist/index.js'
