name: "Test Action"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  unit_tests:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Node.js
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16.x
    - run: npx npm@6 ci
    - run: npx npm@6 test

  # test action works running from the graph
  test:
    name: "Run Action"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        file: test.json
