name: "Test Action"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  unit_tests:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Node.js
      uses: actions/setup-node@v3.5.0
      with:
        node-version: 16.x
    - run: npx npm@6 ci
    - run: npx npm@6 test

  # test action works running from the graph
  test:
    name: "Run Action"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Action
      id: action
      uses: ./
      with:
        file: test.json
    - name: Check output
      shell: pwsh
      run: |
        if ("${{ steps.action.outputs.foo }}" -ne "bar")
        {
          echo "The action did not transform the json file properly."
          exit 1
        }

